services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_swoole_app
    ports:
      - "9501:9501"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "base64:3NR6+mmzeu9P51HwfKPi275jYW1zLPdIq9+9miZAQTk="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: password
      SWOOLE_HTTP_HOST: 0.0.0.0
      SWOOLE_HTTP_PORT: 9501

  db:
    image: mysql:8.0
    container_name: laravel_swoole_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: